config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'dashboards#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end


  get '/transactions/new' => 'transactions#new'
  get '/transactions' => 'transactions#index'
  get '/transactions/transfer' => 'transactions#transfer'
  post '/transactions/transfer' => 'transactions#transfer'
  get '/transactions/load' => 'transactions#load'
  post '/transactions/load' => 'transactions#load'
  post '/transactions/timeout' => 'transactions#timeout'
  post '/transactions/create' => 'transactions#create'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user

  TRANSACTION_TYPES = [
    'load', 'transfer'
  ]
end

app/models/user.rb
class User < ApplicationRecord
  has_one :account
  has_many :transactions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Create user account while creating user model
  after_create do |user|
    Account.create!(
      :user_id => user.id,
      :account_balance => 0
    )
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(
        :phone_number,
        :name,
        :email,
        :password
        )
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @accounts = Account.all
    @account_balance = account_balance
  end

  private

  def account_balance
    current_user.account.account_balance.to_i
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def timeout
    puts params
  end

  def index
    @transactions = Transaction.all
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = TransactionCreator.new(transaction_params).call
    @transaction.save!
  end


  def transfer
    render template: 'transactions/_transfer'
  end

  def load
    render template: 'transactions/_load'
  end

  private

  def transaction_params
    params.permit(
      :transaction_type,
      :sender_id,
      :receiver_id,
      :amount
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/dashboards/index.html.erb
<div class='container'>
  <% if @accounts.size == 0%>
    <p>This user has no account</p>
  <% else %>
    <p> Hey, <%= current_user.name%>!</p>
    Your account's balance is: <%= @account_balance %>
    <% if @account_balance == 0 %>
      <p> Please top up your account <%= link_to 'Top Up', transactions_new_path %></p>
    <% else %>
      <p> Transfer money to a number of your choosing</p>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MShare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
    <%= render 'partials/navbar' %>
    <%= render 'partials/flashes' %>

    <div class='container-fluid'>

      <%= yield %>
    </div>

  </body>
</html>

app/views/partials/_flashes.html.erb
<div class="container flashes">
  <% if flash %>
    <% flash.each do |flash_type, text| %>
      <% if flash_type == 'notice'%>
        <div class='alert alert-success' role='alert'>
          <%= text %>
        </div>
      <% else %>
        <div class="alert alert-danger" role="alert">
          <%= text %>
        </div>
      <% end %>
    <% end %>
<% end %>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">M-Share</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <%- if user_signed_in? %>
        <li class='nav-item'><%= link_to 'Home', authenticated_root_path %></li>
        <li class='nav-item'><%= link_to 'Transactions', transactions_path %></li>
        <li class='nav-item'><a href='#'>Wallet <span class='badge'>$ <%= current_user.account.account_balance%></span></a></li>
        <li class='nav-item'><%= link_to 'Sign Out', destroy_user_session_path, method: 'delete' %></li>
        <li class='nav-item nohref'>
          <a nohref>
          Hey, <%= current_user.name %>
          </a>
        </li>
        <% else %>
        <li class='nav-item'><%= link_to 'Log in', new_user_session_path %></li>
        <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/transactions/_form.html.erb
<h4>Getting Started</h4>

app/views/transactions/_load.html.erb
<div class='container form'>
  <h2>Load Money to Wallet</h2>
  <hr>

  <form action='/transactions/load' method='post'>
    <div class='form-group'>
      <label> Your phone number</label>
      <input type='number' placeholder='+254707001213' class='form-control' required>
    </div>
    <div class='form-group'>
      <label> Amount</label>
      <input type='number' placeholder='Enter amount to transfer' class='form-control' required>
    </div>
    <div class='form-group'>
      <button class='btn btn-primary'>Deposit</button>
      &nbsp; &nbsp;
      <span><%= link_to 'Transfer', transactions_transfer_path%></span>
    </div>
  </form>
</div>

app/views/transactions/_transfer.html.erb
<div class='container form'>
  <h2>Money Transfer</h2>
  <hr>

  <form action='/transactions/transfer' method='post'>
    <div class='form-group'>
      <label> Your phone number</label>
      <input type='number' placeholder='+254707001213' class='form-control' required>
    </div>
    <div class='form-group'>
      <label> Receiver's phone number</label>
      <input type='number' placeholder='+254707001213' class='form-control' required>
    </div>
    <div class='form-group'>
      <label> Amount to transfer</label>
      <input type='number' placeholder='Enter amount to transfer' class='form-control' required>
    </div>
    <div class='form-group'>
      <button class='btn btn-primary'>Transfer</button>
    </div>
  </form>
</div>

app/views/transactions/index.html.erb
<div class='container'>
  <% if @transactions.size == 0%>
    <p>Hey, <%= current_user.name %>. You have not made any transactions made</p>
    <p><%= link_to 'Begin here', transactions_new_path %></p>
  <% else %>
    <p>Below are your transactions</p>
    <%= @transactions.all %>
  <% end %>
</div>

app/views/transactions/new.html.erb
<div class='container'>
<div class='form'>
  <h2>Choose a new Transaction</h2>
  <%= form_for @transaction, url: transactions_load_path do |t| %>
    <div class='form-group'>
      <%= t.label :transaction_type %>
      <%= t.select :transaction_type, Transaction::TRANSACTION_TYPES, {}, class:'form-control' %>
    </div>
    <div class='form-group'>
      <%= t.submit 'Commence', class:'btn btn-primary'%>
    </div>
    <% end %>
  </div>
</div>